### ISSUE TITLE
Set border-box as default

### ISSUE THREAD

**Issue by thamas** [fourkitchens/emulsify#297] opened 2018-10-11 09:23 UTC
danny_englander [4:35 PM]
One thing I noticed about Emulsify, it does not have a global CSS Box model assigned so I was finding that at very narrow widths, padding of various elements would cause the page to be off and there would be a gap on the right side. I added a global `border: box` property and that seemed to fix everything. I wonder if Emulsify just does not want to be too presumptuous in that case?

Johnny5th [4:37 PM]
I noticed, at least on the emulsify version I was on, that was the case too. yet PL added it internally
would look great in PL but the output didn’t have it

danny_englander [4:37 PM]
ahh interesting. Mainly I found this issue with edge to edge content.

Johnny5th [4:38 PM]
you’re meaning `box-sizing: border-box`, right? (edited)

danny_englander [4:39 PM]
yes correct
so I typically use something like this and it's always solved some of those narrow width viewport issues with edge to edge or padding things.
```
html {
  box-sizing: border-box;
  overflow-y: scroll;
  font-size: 100%;
  position: relative;
  width: 100%;
}

*,
*::before,
*::after {
  box-sizing: inherit;
}
```

Johnny5th [4:40 PM]
interesting. I usually only sprinkle in border-box when I need it. maybe I should switch to global

markconroy [4:40 PM]
Switch. To. Global.

danny_englander [4:41 PM]
yeah I guess milage may vary but I think it's one of those things you need to set from the get -go

jsheffers [4:41 PM]
Agreed, we use it everywhere

markconroy [4:41 PM]
```
html {
  box-sizing: border-box;
}

*,
*::after,
*::before {
  box-sizing: inherit;
}
```

bjlewis2 [4:41 PM]
Agreed. I assume that's set, and am confused by everything when it's not

Johnny5th [4:42 PM]
old habits die hard
I still think in old box model

markconroy [4:42 PM]
And you’re a maintainer of emulsify!

bjlewis2 [4:42 PM]
**If it's not already set in Emulsify by now, will someone please submit a PR?**
I will commit it TODAY!

**Comment by sinyayadynya** [comment] 2018-10-17 12:14
I guess https://github.com/fourkitchens/emulsify/issues/295 is a duplicate of this one.

**Closed** 2018-11-26 15:51 UTC
