### ISSUE TITLE
Failed to extract the starterkit

### ISSUE THREAD

**Issue by igorlakic** [fourkitchens/emulsify#209] opened 2018-03-10 21:23 UTC
`failed to extract the starterkit. easiest solution is to manually download it and copy <path>./dist</path to ./source/`

This error appeared yesterday when I tried to install Emulsify on the dev environment with PHP 7.2. There are no similar issues with PHP 7.1. 
I guess that something similar also happened in [#147](https://github.com/fourkitchens/emulsify/issues/147), but with some other PHP version (maybe with 7.1.9 or something like that)...

**Comment by evanmwillhite** [comment] 2018-05-15 14:54
@igorlakic Does this issue still exist or is it a duplicate of #147?

**Comment by igorlakic** [comment] 2018-05-18 13:04
@evanmwillhite I haven't tried it again since my previous comment. It works nice with PHP 7.1...

**Comment by evanmwillhite** [comment] 2018-05-18 15:45
OK, I'm gonna close and we can always reopen if needed. Thank you!

**Closed by evanmwillhite** 2018-05-18 15:45 UTC
