### ISSUE TITLE
[RuntimeException] at npm install

### ISSUE THREAD

**Issue by finkenmann** [fourkitchens/emulsify#180] opened 2017-11-14 13:47 UTC
Hi

I’m a newby with all this composer stuff used in terminal and got the following error, during step 5 from the composer based installation process:
Step 1 to 4 were running all fine and i did a subtheme in my custom theme directory. At step 5 npm install i got the following error (or is it just a message?) within a red warning background: 

`
[Composer\Downloader\TransportException]
  Could not authenticate against github.com
`
I see that inside my sub theme there is a pattern-lab folder and in the vendor folder in the project root, the drupal-pattern-lab folder is installed. Now i’m really unsure, if the installation faild, or if i can use it? Is there a way to check, if everything is fine, or do i have to care about the message in red? There is no error on the right side of the terminal, like normaly an error occured.

Maybe it's helpful, if i post the last couple of lines, the terminal outputed after the npm install command:

```
... 
...
Installing drupal-pattern-lab/edition-twig-standard (v2.2.2)
  - Installing drupal-pattern-lab/edition-twig-standard (v2.2.2): Loading from cache
Created project in pattern-lab
> PatternLab\Installer::setProjectInstall
> PatternLab\Installer::getSuggestedStarterKits
> PatternLab\Installer::getConfigOverrides
Loading composer repositories with package information


  [Composer\Downloader\TransportException]
  Could not authenticate against github.com


create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-s
ecure-http] [--keep-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN emulsify@1.0.0 No repository field.
npm WARN emulsify@1.0.0 No license field.

added 1406 packages in 99.759s
iMac:polytronic_emu pierre$
```

**Comment by amazingrando** [comment] 2017-11-14 14:15
@finkenmann What is happening here is that after all of the npm packages are installed the [post install scripts](https://github.com/fourkitchens/emulsify/blob/develop/package.json#L11) are run. These scripts call out to Github for Pattern Lab and that is where the problem is happening.

The good thing is that this is usually a random timeout and can be fixed by:

- `rm -rf node_modules` to remove the node modules folder inside the theme
- `npm i` again to run through the installation again.

Please try that and post again with whether or not that works.

**Comment by finkenmann** [comment] 2017-11-14 14:45
@amazingrando  Thanks for your quick response. I did remove the node_modules folder and the npm install again. Have the same message with almost the same output, except the last 5 lines are a little bit different, but the added packages are the same.

The site is up and running. The status report page looks fine. Drupal is 8.4.2, php 7.1.6. The system is running on my local Mac with MAMP.

```
Installing drupal-pattern-lab/edition-twig-standard (v2.2.2)
  - Installing drupal-pattern-lab/edition-twig-standard (v2.2.2): Loading from cache

Created project in pattern-lab
> PatternLab\Installer::setProjectInstall
> PatternLab\Installer::getSuggestedStarterKits
> PatternLab\Installer::getConfigOverrides
Loading composer repositories with package information


  [Composer\Downloader\TransportException]
  Could not authenticate against github.com


create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-U
RL] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--no-install] [--ign
ore-platform-reqs] [--] [<package>] [<directory>] [<version>]

npm WARN emulsify@1.0.0 No repository field.
npm WARN emulsify@1.0.0 No license field.

added 1406 packages in 79.08s
iMac:polytronic_emu pierre$
```

**Comment by ModulesUnraveled** [comment] 2017-11-14 14:51
It looks like this might be a Github thing. A quick google search brought me here: https://getcomposer.org/doc/articles/troubleshooting.md#api-rate-limit-and-oauth-tokens

Try creating an OAuth token in Github and then running the `composer config -g github-oauth.github.com <oauthtoken>` command, then delete the node_modules folder and try installing again.

**Comment by amazingrando** [comment] 2017-11-14 14:51
@finkenmann Looking around this might be Github rate limiting. Try adding a Github auth token to composer: https://getcomposer.org/doc/articles/troubleshooting.md#api-rate-limit-and-oauth-tokens

**Comment by amazingrando** [comment] 2017-11-14 14:51
@ModulesUnraveled JINX

**Comment by finkenmann** [comment] 2017-11-14 15:17
wohooo.. 👍 

It worked. Thanks a lot. Even if i don’t know, what i did ;-)
Do i have to select scopes? I’ll kept everything uncheckt and is this token stored in my composer settings somewhere or is this only a temporary thing?

Regards from Switzerland

**Comment by amazingrando** [comment] 2017-11-14 15:25
> Do i have to select scopes?
I don't know.

> It worked. Thanks a lot.
Yay! I'm glad to hear this.

**Closed by amazingrando** 2017-11-14 15:25 UTC
